#!/bin/bash
echo "=== Checking available signing tools ==="
echo ""
echo "fastlane: $(which fastlane 2>/dev/null || echo 'NOT FOUND')"
echo "fastlane version: $(fastlane --version 2>/dev/null | head -2 || echo 'N/A')"
echo ""
echo "ruby: $(which ruby 2>/dev/null || echo 'NOT FOUND')"
echo "gem: $(which gem 2>/dev/null || echo 'NOT FOUND')"
echo ""
echo "xcrun: $(which xcrun 2>/dev/null || echo 'NOT FOUND')"
echo ""
echo "=== Installed provisioning profiles ==="
ls ~/Library/MobileDevice/Provisioning\ Profiles/ 2>/dev/null || echo "None"
echo ""
echo "=== Keychain signing identities ==="
security find-identity -v -p codesigning 2>/dev/null | grep -E "Apple|iPhone"
echo "Done"
